version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: spring_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tickets
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-network

  app:
    image: openjdk:21
    container_name: spring_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./:/app
    working_dir: /app
    command: ./gradlew bootRun
    networks:
      - spring-network

volumes:
  postgres_data:

networks:
  spring-network:
